version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: estadio_db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=estadio_virtual_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: